<?php


namespace Source\Models;


use Source\Core\Model;

class Task extends Model
{
    public function __construct()
    {
        parent::__construct("tasks", ["id"], ["name", "datetime"]);
    }

    public function save(): bool
    {
        if(!$this->user_id){
            $this->user_id = Auth::user()->id;
        }
        return parent::save(); // TODO: Change the autogenerated stub
    }

    public function datetime()
    {
        $dt = (new \DateTime($this->datetime ?? "now"));
        $dtnow = date_create('now');

        $return = new \stdClass();
        $return->date = $dt->format("d/m/Y");
        $return->time = $dt->format("H:i");
        $return->daysuntil = date_diff($dtnow, $dt);
        return $return;
    }
}